2015-02-14T04:37:08.311174+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 624, in run_simple
2015-02-14T04:37:08.311181+00:00 app[web.1]:     passthrough_errors, ssl_context)
2015-02-14T04:37:08.311194+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/SocketServer.py", line 434, in server_bind
2015-02-14T04:37:08.610134+00:00 heroku[web.1]: State changed from starting to up
2015-02-14T04:37:38.391517+00:00 app[web.1]: [2015-02-14 04:37:38 +0000] [3] [INFO] Reason: Worker failed to boot.
2015-02-14T04:37:38.391344+00:00 app[web.1]: [2015-02-14 04:37:38 +0000] [3] [INFO] Shutting down: Master
2015-02-14T04:37:39.251324+00:00 heroku[web.1]: Process exited with status 3
2015-02-14T04:37:39.268586+00:00 heroku[web.1]: State changed from up to crashed
2015-02-14T04:39:00.700106+00:00 heroku[api]: Scale to web=1 by info@wearhacks.com
2015-02-14T04:39:09.548528+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arcane-spire-6055.herokuapp.com request_id=090bd537-112e-42f6-b327-9321496f4c09 fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:39:10.041842+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=arcane-spire-6055.herokuapp.com request_id=1db93b46-8663-47a8-a1e6-205e5e7de76e fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:49:45.337087+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arcane-spire-6055.herokuapp.com request_id=ebf64e6a-741a-4ff1-8242-3920066b294c fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:49:45.908714+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=arcane-spire-6055.herokuapp.com request_id=af79de9d-8e05-4cd0-ac0f-fdc1ef7592f7 fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:49:52.131592+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arcane-spire-6055.herokuapp.com request_id=c311f0f6-d10b-4a2b-9090-6e4a7f359798 fwd="54.224.74.223" dyno= connect= service= status=503 bytes=
2015-02-14T04:49:54.794353+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arcane-spire-6055.herokuapp.com request_id=a02996f1-4ea4-4f61-b603-7db4fb6b88ab fwd="50.135.217.165" dyno= connect= service= status=503 bytes=
2015-02-14T04:49:55.969576+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=arcane-spire-6055.herokuapp.com request_id=b9179926-a544-4ab3-b4d9-8ad83eb14541 fwd="50.135.217.165" dyno= connect= service= status=503 bytes=
2015-02-14T04:50:02.250938+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arcane-spire-6055.herokuapp.com request_id=a6f73b41-8729-4b0f-ba62-cdaa89640944 fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:50:02.688663+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=arcane-spire-6055.herokuapp.com request_id=610e4f27-9d95-43ef-b2e3-db11c441cf42 fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:52:11.852299+00:00 heroku[api]: Scale to web=1 by info@wearhacks.com
2015-02-14T04:52:17.383491+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arcane-spire-6055.herokuapp.com request_id=bce1feab-2f60-4309-9b1d-823283d13a85 fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:52:17.982314+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=arcane-spire-6055.herokuapp.com request_id=b44ea015-8560-4803-9beb-a2a65eeff19f fwd="70.50.9.144" dyno= connect= service= status=503 bytes=
2015-02-14T04:55:31.774043+00:00 heroku[web.1]: State changed from crashed to starting
2015-02-14T04:55:35.368380+00:00 heroku[web.1]: Starting process with command `gunicorn runp:app`
2015-02-14T04:55:37.139378+00:00 app[web.1]: [2015-02-14 04:55:37 +0000] [3] [INFO] Listening at: http://0.0.0.0:48048 (3)
2015-02-14T04:55:37.139464+00:00 app[web.1]: [2015-02-14 04:55:37 +0000] [3] [INFO] Using worker: sync
2015-02-14T04:55:37.147555+00:00 app[web.1]: [2015-02-14 04:55:37 +0000] [9] [INFO] Booting worker with pid: 9
2015-02-14T04:55:37.390259+00:00 app[web.1]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2015-02-14T04:55:37.390286+00:00 app[web.1]:  * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
2015-02-14T04:55:37.138825+00:00 app[web.1]: [2015-02-14 04:55:37 +0000] [3] [INFO] Starting gunicorn 19.2.1
2015-02-14T04:55:37.200234+00:00 app[web.1]: [2015-02-14 04:55:37 +0000] [10] [INFO] Booting worker with pid: 10
2015-02-14T04:55:37.393981+00:00 app[web.1]: [2015-02-14 04:55:37 +0000] [9] [ERROR] Exception in worker process:
2015-02-14T04:55:37.393999+00:00 app[web.1]:     __import__(module)
2015-02-14T04:55:37.394007+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 602, in inner
2015-02-14T04:55:37.393989+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-02-14T04:55:37.393991+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-02-14T04:55:37.394001+00:00 app[web.1]:     app.run(debug = False)
2015-02-14T04:55:37.394012+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 440, in __init__
2015-02-14T04:55:37.394017+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/SocketServer.py", line 443, in server_activate
2015-02-14T04:55:37.394039+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/base.py", line 67, in wsgi
2015-02-14T04:55:37.393988+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
2015-02-14T04:55:37.393994+00:00 app[web.1]:     return self.load_wsgiapp()
2015-02-14T04:55:37.394004+00:00 app[web.1]:     run_simple(host, port, self, **options)
2015-02-14T04:55:37.394014+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/SocketServer.py", line 421, in __init__
2015-02-14T04:55:37.394031+00:00 app[web.1]: error: [Errno 98] Address already in use
2015-02-14T04:55:37.394032+00:00 app[web.1]: Traceback (most recent call last):
2015-02-14T04:55:37.394034+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
2015-02-14T04:55:37.394035+00:00 app[web.1]:     worker.init_process()
2015-02-14T04:55:37.394036+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/workers/base.py", line 116, in init_process
2015-02-14T04:55:37.394037+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2015-02-14T04:55:37.393993+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-02-14T04:55:37.394016+00:00 app[web.1]:     self.server_activate()
2015-02-14T04:55:37.394043+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-02-14T04:55:37.393987+00:00 app[web.1]:     worker.init_process()
2015-02-14T04:55:37.393992+00:00 app[web.1]:     self.callable = self.load()
2015-02-14T04:55:37.394003+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 772, in run
2015-02-14T04:55:37.394018+00:00 app[web.1]:     self.socket.listen(self.request_queue_size)
2015-02-14T04:55:37.394040+00:00 app[web.1]:     self.callable = self.load()
2015-02-14T04:55:37.394048+00:00 app[web.1]:   File "/app/runp.py", line 2, in <module>
2015-02-14T04:55:37.394053+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 624, in run_simple
2015-02-14T04:55:37.394054+00:00 app[web.1]:     inner()
2015-02-14T04:55:37.393984+00:00 app[web.1]: Traceback (most recent call last):
2015-02-14T04:55:37.393996+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-02-14T04:55:37.394005+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 624, in run_simple
2015-02-14T04:55:37.394011+00:00 app[web.1]:     passthrough_errors, ssl_context)
2015-02-14T04:55:37.394046+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-02-14T04:55:37.394062+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/SocketServer.py", line 421, in __init__
2015-02-14T04:55:37.393986+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/arbiter.py", line 503, in spawn_worker
2015-02-14T04:55:37.393998+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/util.py", line 355, in import_app
2015-02-14T04:55:37.394006+00:00 app[web.1]:     inner()
2015-02-14T04:55:37.394030+00:00 app[web.1]:     return getattr(self._sock,name)(*args)
2015-02-14T04:55:37.394042+00:00 app[web.1]:     return self.load_wsgiapp()
2015-02-14T04:55:37.394059+00:00 app[web.1]:     passthrough_errors, ssl_context)
2015-02-14T04:55:37.394079+00:00 app[web.1]:     return getattr(self._sock,name)(*args)
2015-02-14T04:55:37.394009+00:00 app[web.1]:     passthrough_errors, ssl_context).serve_forever()
2015-02-14T04:55:37.394049+00:00 app[web.1]:     app.run(debug = False)
2015-02-14T04:55:37.394067+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/socket.py", line 224, in meth
2015-02-14T04:55:37.393995+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2015-02-14T04:55:37.394010+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 512, in make_server
2015-02-14T04:55:37.394029+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/socket.py", line 224, in meth
2015-02-14T04:55:37.394050+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/flask/app.py", line 772, in run
2015-02-14T04:55:37.394061+00:00 app[web.1]:     HTTPServer.__init__(self, (host, int(port)), handler)
2015-02-14T04:55:37.394066+00:00 app[web.1]:     self.socket.listen(self.request_queue_size)
2015-02-14T04:55:37.394000+00:00 app[web.1]:   File "/app/runp.py", line 2, in <module>
2015-02-14T04:55:37.394041+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2015-02-14T04:55:37.394060+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 440, in __init__
2015-02-14T04:55:37.394013+00:00 app[web.1]:     HTTPServer.__init__(self, (host, int(port)), handler)
2015-02-14T04:55:37.394044+00:00 app[web.1]:     return util.import_app(self.app_uri)
2015-02-14T04:55:37.394055+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 602, in inner
2015-02-14T04:55:37.394047+00:00 app[web.1]:     __import__(module)
2015-02-14T04:55:37.394052+00:00 app[web.1]:     run_simple(host, port, self, **options)
2015-02-14T04:55:37.394058+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/site-packages/werkzeug/serving.py", line 512, in make_server
2015-02-14T04:55:37.394065+00:00 app[web.1]:   File "/app/.heroku/python/lib/python2.7/SocketServer.py", line 443, in server_activate
2015-02-14T04:55:37.394099+00:00 app[web.1]: [2015-02-14 04:55:37 +0000] [9] [INFO] Worker exiting (pid: 9)
2015-02-14T04:55:37.394056+00:00 app[web.1]:     passthrough_errors, ssl_context).serve_forever()
2015-02-14T04:55:37.394063+00:00 app[web.1]:     self.server_activate()
2015-02-14T04:55:37.394081+00:00 app[web.1]: error: [Errno 98] Address already in use
2015-02-14T04:55:37.740245+00:00 heroku[web.1]: State changed from starting to up
2015-02-14T04:56:07.466231+00:00 app[web.1]: [2015-02-14 04:56:07 +0000] [3] [INFO] Reason: Worker failed to boot.
2015-02-14T04:56:07.466148+00:00 app[web.1]: [2015-02-14 04:56:07 +0000] [3] [INFO] Shutting down: Master
2015-02-14T04:56:08.248810+00:00 heroku[web.1]: State changed from up to crashed
2015-02-14T04:56:08.231718+00:00 heroku[web.1]: Process exited with status 3
